dj4e-assignment/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/create/', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>/', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

dj4e-assignment/mysite/mysite/urls.py
import os

from django.conf.urls import url
from django.views.static import serve


from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView



admin.autodiscover()
admin.site.enable_nav_sidebar = False

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),


    path('accounts/', include('django.contrib.auth.urls')),  # Add
    path('autos/', include('autos.urls')),                   # Add
    path('cats/', include('cats.urls')),
    path('hello/', include('hello.urls')),
    path('ads/', include('ads.urls')),

    path('polls/', include('polls.urls')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),

]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]


# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

dj4e-assignment/mysite/ads/models.py
from django.db import models

from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

from PIL import Image

# Create your models here.


class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Picture
    picture = models.ImageField(default='ad_pics/default.jpg', upload_to='ad_pics')


    def save(self, *args, **kwargs):
        super(Ad, self).save(*args, **kwargs)

        # ReScale the Uploaded Image:
        picture = Image.open(self.picture.path) ## GCP Error
        #image = Image.open(self.picture.name) ## GCP Error
        if(picture.height > 300 or picture.width > 300):
            output_size = (300, 300)
            picture.thumbnail(output_size) # resize the image

            picture.save(self.picture.path)  ## GCP Error
            #image.save(self.image.name)  ## GCP Error


    # Shows up in the admin list
    def __str__(self):
        return self.title



class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class Fav(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self):
        return f'({self.id}) {self.user.username} likes {self.ad.title[:10]}'

dj4e-assignment/mysite/ads/forms.py
from django import forms
from ads.models import Ad


class CreateForm(forms.ModelForm):

    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'picture']  # Picture is manual


#from django.core.exceptions import ValidationError
#from django.core import validators

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

dj4e-assignment/mysite/ads/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from ads.models import Ad, Comment, Fav
from ads.advance_views import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

from ads.forms import CreateForm, CommentForm
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse

from django.db.models import Q


class AdListView(OwnerListView):
    model = Ad
    #paginate_by = 3
    # By convention:
    # template_name = "ads/ad_list.html"

    def get_context_data(self, **kwargs):
        # return the origianl context with 'ad_list' and 'favorites':
        context = super().get_context_data(**kwargs)

        ### Display the Favorites -
        favs = list()
        if self.request.user.is_authenticated:
            # get the list of their favorite ads but only the id's.
            # now, we have the ad_list, add the favorites:
            favsQuerySet = self.request.user.fav_set.values('ad_id') # we will get all the current user favorites ads id's.
            favs = list(favsQuerySet.values_list('ad_id', flat=True))

        context['favorites'] = favs

        ### Search Box -
        searchTerm = self.request.GET.get("search", False)
        if searchTerm:
            # Title only Search-
            # Multi-field Search -
            searchQuery = Ad.objects.filter(Q(title__contains=searchTerm) | Q(text__contains=searchTerm)).order_by('-updated_at')

            context['ad_list'] = searchQuery #if no searchTerm - 'ad_list' will be all the ads.


        context['search'] = searchTerm


        return context


class AdDetailView(OwnerDetailView):
    model = Ad

    # https://stackoverflow.com/questions/21758731/how-can-i-get-pk-or-id-in-get-context-data-from-cbv
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        adQuery = get_object_or_404(Ad, id=pk)
        comments = Comment.objects.filter(ad=adQuery).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad': adQuery, 'comments': comments, 'comment_form': comment_form }
        return context


    '''
    def get(self, request, pk):
        # It's like Charles's "forums/views.py", but because its just a context modification I
        # Used 'get_cintext_data' instead. (see above)

        # get the current Ad Object.
        adQuery = get_object_or_404(Ad, id=pk)
        # get all the comments of it
        comments = Comment.objects.filter(ad=adQuery).order_by('-updated_at')
        # build a new comment form
        comment_form = CommentForm()
        # build context
        context = { 'ad': adQuery, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)
        '''



class AdCreateView(OwnerCreateView):
    model = Ad
    #fields = ['title','price', 'text']
    fields = ['title', 'price', 'text', 'picture']  # Picture is manual


class AdUpdateView(OwnerUpdateView):
    model = Ad
    #fields = ['title','price', 'text']
    fields = ['title', 'price', 'text', 'picture']  # Picture is manual


class AdDeleteView(OwnerDeleteView):
    model = Ad


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        # get the current ad
        currentAd = get_object_or_404(Ad, id=pk)
        # create a new Comment Object. (request.POST['comment'] - Came from the comment_form)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=currentAd)
        # save
        comment.save()
        # return
        return redirect(reverse('ads:ad_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = 'ads/comment_delete.html'

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    # get a post HTTP request - create a new fav entry - and response 200.
    def post(self, request, pk):
        adQuery = get_object_or_404(Ad, id=pk)
        fav, created = Fav.objects.get_or_create(user=request.user, ad=adQuery)
        try:
            fav.save()
        except IntegrityError as e:
            print("Error: ", e)

        return HttpResponse()



@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    # Get a post HTTP request - delete the fav entry - and response 200 ok.
    def post(self, request, pk):
        # search for the ad with the 'pk' id, search for the entry of (request.user,ad) and remove it.
        adQuery = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=adQuery)
            fav.delete()
        except Fav.DoesNotExist as e:
            print("Error: ", e)

        return HttpResponse()

dj4e-assignment/mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "./base_menu.html" %}

{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

dj4e-assignment/mysite/ads/templates/ads/ad_detail.html
{% extends "./base_menu.html" %}

{% load humanize %}
<!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
  }
</style>

{% endblock %}

{% block content %}

    <p>
    {% if ad.picture.url %}
        <div id="overlay" class="overlay" style="text-align: center;" onclick="document.getElementById('overlay').style.display = 'none';">
            <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{{ ad.picture.url }}">
        </div>
    {% endif %}

    <span style="float: right;">
        ({{ ad.updated_at|naturaltime }})

        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </span>
    </p>

    <h1>{{ ad.title }}</h1>
    {% if ad.picture.url %}
        <img style="float:right; max-width:50%;" src="{{ ad.picture.url }}" onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}

    <p>
        {{ ad.text }}
        <br>
        ({{ ad.updated_at|naturaltime }})
    </p>

    <br clear="all" />
    <!-- Comments section -->

    <!-- a form to add new comments -->
    {% if user.is_authenticated %}
        <!-- Show the form -->
        <p>
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" value="Submit">
                <input type="submit" value="All Forums" onclick="window.location.href='{% url 'ads:all' %}';return false;">
            </form>
        </p>
    {% endif %}

    <!-- Show all comments -->
    <p>
        <ul class="list-group">
        {% for comment in comments %}
            <li {% if forloop.counter0|divisibleby:"2" %} class="list-group-item list-group-item-info" {% else %} class="list-group-item" {% endif %} style="color: black">
                {{ comment.text }}
                ({{ comment.updated_at|naturaltime }})
                {% if user == comment.owner %}
                    <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    </p>


    <p>
        <a href="{% url 'ads:all' %}">All Ads</a>
    </p>
{% endblock %}

dj4e-assignment/mysite/ads/templates/ads/ad_form.html
{% extends "./base_menu.html" %}


{% load crispy_forms_tags %}


{% block content %}
<p>
    <b>article form</b>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <!-- <input type="submit" value="Submit"> -->
        <button type="submit">Submit</button>

        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
    </form>
</p>

<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>


  $("#upload_form").submit(
    function ()
    {
      console.log('Checking file size');
      console.log({{ form.max_upload_limit }});

      if (window.File && window.FileReader && window.FileList && window.Blob)
      {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if(file && file.size > {{ form.max_upload_limit }} )
        {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
          return false;
        }
      }

    });

</script>

{% endblock %}

dj4e-assignment/mysite/ads/templates/ads/ad_list.html
{% extends "./base_menu.html" %}

{% block content %}
    <h2>Ads list</h2>

    <div class="container">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
        <span style="float: right">
            <form>
                <input type="text" placeholder="Search.." name="search"
                {% if search %} value="{{ search }}" {% endif %}>
                <button type="submit"><i class="fa fa-search"></i></button>
                <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
            </form>
        </span>

    </div>

    <!-- bootstrap 3 -->
    <!-- https://getbootstrap.com/docs/3.3/components/ -->
    <div class="container">

        {% if ad_list %}

            <ul class="list-group">
                {% for ad in ad_list %}

                    <li {% if forloop.counter0|divisibleby:"2" %} class="list-group-item list-group-item-success" {% else %} class="list-group-item" {% endif %} style="color: black">
                        <!--  https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#ifequal-and-ifnotequal  -->
                        <!--  https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#divisibleby  -->
                        <a href="{% url 'ads:ad_detail' ad.id %}">{{ forloop.counter0 }} {{ ad.title }}</a> <!-- The grader identify it as two items -->

                        <!-- Not protect, just do not display! -->
                        {% if ad.owner == user %}
                            <span style="float: right">
                                (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> | <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
                            </span>
                        {% endif %}


                        <!-- Favorites -->
                        {% if user.is_authenticated %}

                            <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                            <a href="#" onclick="favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
                                {% if ad.id not in favorites %} style="display: none;" {% endif %}
                                id="favorite_star_{{ad.id}}">

                                <span class="fa-stack" style="vertical-align: middle;">
                                    <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                    <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                            </a>

                            <!-- the second href -->
                            <a href="#" onclick="favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                                {% if ad.id in favorites %} style="display: none;" {% endif %}
                                id="unfavorite_star_{{ad.id}}">

                                <span class="fa-stack" style="vertical-align: middle;">
                                    <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                    <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                            </a>
                        {% endif %}
                        <br/>

                        <div style="left:10px">
                            {% if ad.text|length < 20 %}
                                {{ ad.text }}
                            {% else %}
                                {{ ad.text|slice:"0:19" }}
                                <a href="{% url 'ads:ad_detail' ad.id %}">...</a>
                            {% endif %}
                        </div>

                        <small>
                            {% if ad.owner.username %}
                                posted by {{ ad.owner.username }},
                            {% endif %}
                            {{ ad.updated_at }}

                        </small>
                        <!--<hr>-->

                    </li>


                {% endfor%}
            </ul>

        {% else %}
            <strong>No Ad was found !</strong>
        {% endif %}
    </div>

    <!--
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    -->

    <p>
        <a href="{% url 'ads:ad_create' %}">Add an Ad</a>
    </p>

    <p>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
        {% else %}
          <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        {% endif %}
    </p>

<script>
function favPost(url, ad_id)
{
    console.log('Requesting JSON');
    //let csrf = csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value;
    $.post(url, {},  function(rowz)
    {
        // https://api.jquery.com/jquery.post/
        $("#unfavorite_star_"+ad_id).toggle();
        $("#favorite_star_"+ad_id).toggle();
        // Each call toggle both so it seems like the star is change its internal color
        console.log(url, 'finished');

    }).fail(function(xhr)
    {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>

{% endblock %}

dj4e-assignment/mysite/ads/templates/ads/base_menu.html
{% extends "base_bootstrap.html" %}

{% block navbar %}
{% load app_tags %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads' as ads %}
      <li {% if request.get_full_path == ads %}class="active"{% endif %}>
          <a href="{% url 'ads:all' %}">Ads</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'ads:ad_create' %}">Create Ad</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>

{% endblock %}

dj4e-assignment/mysite/ads/templates/ads/comment_delete.html
{% extends "./base_menu.html" %}

{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete the comment: {{ comment }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit"  class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}